CC = gcc 
AR = ar
CFLAGS = -g -c -O2 -D_USE_PTHREADS -D__SSE3 -msse3 -D__AVX -fomit-frame-pointer -funroll-loops -Wall -Wredundant-decls  -Wreturn-type  -Wswitch-default -Wimplicit  -Wimplicit-function-declaration  -Wimplicit-int -Wimport -Wunused-label -Wno-int-to-pointer-cast -Wbad-function-cast  -Wmissing-declarations -Wmissing-prototypes  -Wnested-externs  -Wold-style-definition -Wstrict-prototypes -Wpointer-sign -Wextra -Wredundant-decls -Wunused -Wunused-function -Wunused-parameter -Wunused-value  -Wunused-variable -Wformat  -Wformat-nonliteral -Wparentheses -Wsequence-point -Wuninitialized -Wundef -Wbad-function-cast
ARFLAGS = rvs
TARGET = libpll
ARCH = AVX-PTHREADS
VERSION = 1.0.0
STATICLIB = $(TARGET)-$(ARCH).a.$(VERSION)	# static library
SHAREDOBJ = $(TARGET)-$(ARCH).so.$(VERSION)	# shared object
GLOBAL_DEPS = axml.h globalVariables.h
RM = rm -f

OBJ = hash.o stack.o ssort.o queue.o utils.o optimizeModel.o trash.o searchAlgo.o topologies.o treeIO.o models.o evaluatePartialGenericSpecial.o evaluateGenericSpecial.o newviewGenericSpecial.o makenewzGenericSpecial.o bipartitionList.o restartHashTable.o avxLikelihood.o fastDNAparsimony.o randomTree.o lexer.o recom.o genericParallelization.o common.o alignment.o fasta.o phylip.o newick.o part.o


all: $(STATICLIB)

$(STATICLIB) : $(OBJ)
	@echo "==> Building PLL Library ($(STATICLIB))"
	$(AR) $(ARFLAGS) $@ $(OBJ)
	ln -sf $(STATICLIB) $(TARGET)-$(ARCH).a

avxLikelihood.o : avxLikelihood.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -mavx -c -o $@ $<

fastDNAparsimony.o : fastDNAparsimony.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -mavx -c -o $@ $<

genericParallelization.o : genericParallelization.c $(GLOBAL_DEPS)
bipartitionList.o : bipartitionList.c $(GLOBAL_DEPS)
evaluatePartialSpecialGeneric.o : evaluatePartialSpecialGeneric.c $(GLOBAL_DEPS)
optimizeModel.o : optimizeModel.c $(GLOBAL_DEPS)
trash.o : trash.c $(GLOBAL_DEPS)
utils.o : utils.c $(GLOBAL_DEPS)
searchAlgo.o : searchAlgo.c $(GLOBAL_DEPS)
topologies.o : topologies.c $(GLOBAL_DEPS)
treeIO.o : treeIO.c $(GLOBAL_DEPS)
models.o : models.c $(GLOBAL_DEPS)
evaluatePartialGenericSpecial.o : evaluatePartialGenericSpecial.c $(GLOBAL_DEPS)
evaluateGenericSpecial.o : evaluateGenericSpecial.c $(GLOBAL_DEPS)
newviewGenericSpecial.o : newviewGenericSpecial.c $(GLOBAL_DEPS)
makenewzGenericSpecial.o : makenewzGenericSpecial.c $(GLOBAL_DEPS)
randomTree.o : randomTree.c $(GLOBAL_DEPS)
restartHashTable.o : restartHashTable.c $(GLOBAL_DEPS)
recom.o : recom.c  $(GLOBAL_DEPS)
queue.o : queue.c  $(GLOBAL_DEPS)
stack.o : stack.c $(GLOBAL_DEPS)
hash.o : hash.c $(GLOBAL_DEPS)
common.o: parser/common.c
	$(CC) $(CFLAGS) -o $@ $<
alignment.o: parser/alignment/alignment.c
	$(CC) $(CFLAGS) -o $@ $<
phylip.o: parser/alignment/phylip.c
	$(CC) $(CFLAGS) -o $@ $<
fasta.o: parser/alignment/fasta.c
	$(CC) $(CFLAGS) -o $@ $<
newick.o: parser/newick/newick.c
	$(CC) $(CFLAGS) -o $@ $<
part.o: parser/partition/part.c
	$(CC) $(CFLAGS) -o $@ $<
ssort.o : parser/ssort.c
	$(CC) $(CFLAGS) -o $@ $<

clean : 
	-$(RM) *.o $(STATICLIB) $(SHAREDOBJ)

.PHONY: all clean
.INTERMEDIATE: $(OBJ)
