CC = mpicc
AR = ar
CFLAGS = -g -c -O2 -D_FINE_GRAIN_MPI -D__SSE3 -msse3 -O2 -fomit-frame-pointer -funroll-loops -Wall -Wunused-parameter -Wredundant-decls  -Wreturn-type  -Wswitch-default -Wunused-value -Wimplicit  -Wimplicit-function-declaration  -Wimplicit-int -Wimport  -Wunused  -Wunused-function  -Wunused-label -Wno-int-to-pointer-cast -Wbad-function-cast  -Wmissing-declarations -Wmissing-prototypes  -Wnested-externs  -Wold-style-definition -Wstrict-prototypes -Wpointer-sign -Wextra -Wredundant-decls -Wunused -Wunused-function -Wunused-parameter -Wunused-value  -Wunused-variable -Wformat  -Wformat-nonliteral -Wparentheses -Wsequence-point -Wuninitialized -Wundef -Wbad-function-cast
ARFLAGS = rvs
TARGET = libpll
ARCH = SSE3-MPI
VERSION = 1.0.0
STATICLIB = $(TARGET)-$(ARCH).a.$(VERSION)	# static library
SHAREDOBJ = $(TARGET)-$(ARCH).so.$(VERSION)	# shared object
GLOBAL_DEPS = pll.h globalVariables.h
RM = rm -f

OBJ = hash.o stack.o ssort.o queue.o utils.o randomTree.o optimizeModel.o trash.o searchAlgo.o topologies.o fastDNAparsimony.o treeIO.o models.o evaluatePartialGenericSpecial.o evaluateGenericSpecial.o newviewGenericSpecial.o makenewzGenericSpecial.o bipartitionList.o restartHashTable.o recom.o  genericParallelization.o lexer.o common.o alignment.o fasta.o phylip.o ssort.o newick.o part.o

all : $(STATICLIB)

$(STATICLIB) : $(OBJ)
	@echo "==> Building PLL Library ($(STATICLIB))"
	$(AR) $(ARFLAGS) $@ $+
	ln -sf $(STATICLIB) $(TARGET)-$(ARCH).a

fastDNAparsimony.o : fastDNAparsimony.c $(GLOBAL_DEPS)
bipartitionList.o : bipartitionList.c $(GLOBAL_DEPS)
optimizeModel.o : optimizeModel.c $(GLOBAL_DEPS)
trash.o : trash.c $(GLOBAL_DEPS)
searchAlgo.o : searchAlgo.c $(GLOBAL_DEPS)
topologies.o : topologies.c $(GLOBAL_DEPS)
parsePartitions.o : parsePartitions.c $(GLOBAL_DEPS)
treeIO.o : treeIO.c $(GLOBAL_DEPS)
models.o : models.c $(GLOBAL_DEPS)
evaluatePartialGenericSpecial.o : evaluatePartialGenericSpecial.c $(GLOBAL_DEPS)
evaluateGenericSpecial.o : evaluateGenericSpecial.c $(GLOBAL_DEPS)
newviewGenericSpecial.o : newviewGenericSpecial.c $(GLOBAL_DEPS)
makenewzGenericSpecial.o : makenewzGenericSpecial.c $(GLOBAL_DEPS)
restartHashTable.o : restartHashTable.c $(GLOBAL_DEPS)
queue.o : queue.c $(GLOBAL_DEPS)
stack.o : stack.c $(GLOBAL_DEPS)
hash.o : hash.c $(GLOBAL_DEPS)
lexer.o : lexer.c $(GLOBAL_DEPS)
common.o: parser/common.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<
alignment.o: parser/alignment/alignment.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<
phylip.o: parser/alignment/phylip.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<
fasta.o: parser/alignment/fasta.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<
newick.o: parser/newick/newick.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<
part.o: parser/partition/part.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<
ssort.o : parser/ssort.c $(GLOBAL_DEPS)
	$(CC) $(CFLAGS) -o $@ $<

clean : 
	-$(RM) *.o $(STATICLIB) $(SHAREDOBJ)

.PHONY: all clean
.INTERMEDIATE: $(OBJ)
