CC = mpicc
MAKE = make
LIBPATH = ../../
INCPATH = ../../
BIN = pll
PLL = pll
ARCH = SSE3-MPI
LIBRARIES = -l$(PLL)-$(ARCH) -lm
TARGET = $(BIN)-$(ARCH)
RM = rm -f

all: $(BIN)-$(ARCH)

$(BIN)-$(ARCH): main.c
	$(MAKE) -C $(LIBPATH) -f Makefile.$(ARCH)
	@echo "==> Building PLL example ($(BIN)-$(ARCH))"
	$(CC) -D_FINE_GRAIN_MPI $+ -L $(LIBPATH) -I $(INCPATH) $(LIBRARIES) -o $@ 

clean : 
	-$(RM) $(BIN)-$(ARCH)
.PHONY: all clean
